import Link from 'next/link';
import { Logo } from '@/components/Logo';
import { ThemeToggle } from '@/components/ThemeToggle';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — OUTSYD',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--bg-secondary)] text-[var(--text-primary)]">
      <header className="h-16 bg-[var(--bg-card)] border-b border-[var(--border-color)] sticky top-0 z-30">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-full flex items-center justify-between">
          <Link href="/">
            <Logo width={105} height={28} className="h-7 w-auto" priority />
          </Link>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <Link href="/" className="text-xs font-semibold text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors">
              ← Home
            </Link>
          </div>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-2 text-[var(--text-primary)]">Terms of Service</h1>
        <p className="text-sm text-[var(--text-muted)] mb-8">Last updated: September 2026</p>
        <div className="space-y-6 text-sm text-[var(--text-secondary)] leading-relaxed">
          <section className="card-standard bg-[var(--bg-card)] border border-[var(--border-color)] p-6 rounded-xl">
            <h2 className="text-base font-semibold text-[var(--text-primary)] mb-2">Acceptance of Terms</h2>
            <p>By using OUTSYD, you agree to these terms. OUTSYD is provided as-is for informational and planning purposes only.</p>
          </section>
          <section className="card-standard bg-[var(--bg-card)] border border-[var(--border-color)] p-6 rounded-xl">
            <h2 className="text-base font-semibold text-[var(--text-primary)] mb-2">Service Description</h2>
            <p>OUTSYD generates parametric construction cost estimates using research-validated coefficients from CPWD DSR 2024 and regional rate indexes. Estimates are approximations — not substitutes for professional engineering assessments.</p>
          </section>
          <section className="card-standard bg-[var(--bg-card)] border border-[var(--border-color)] p-6 rounded-xl">
            <h2 className="text-base font-semibold text-[var(--text-primary)] mb-2">Limitation of Liability</h2>
            <p>OUTSYD and its creator assume no liability for construction decisions made based on estimates generated by this tool. Users must engage qualified structural engineers and licensed professionals before committing to construction.</p>
          </section>
          <section className="card-standard bg-[var(--bg-card)] border border-[var(--border-color)] p-6 rounded-xl">
            <h2 className="text-base font-semibold text-[var(--text-primary)] mb-2">Intellectual Property</h2>
            <p>OUTSYD, its coefficient engine, and design are created by Ankit Kumar Tiwari. All rights reserved.</p>
          </section>
        </div>
      </div>
    </main>
  );
}
