import Link from 'next/link';
import Image from 'next/image';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — OUTSYD',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="border-b border-slate-100 px-4 py-3">
        <div className="max-w-3xl mx-auto flex items-center gap-3">
          <Link href="/"><Image src="/outsyd-logo.png" alt="OUTSYD" width={100} height={28} className="h-7 w-auto" /></Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold mb-2" style={{ color: '#1e2d4e' }}>Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: September 2026</p>
        <div className="prose prose-sm prose-slate max-w-none space-y-6">
          <section>
            <h2 className="text-lg font-semibold" style={{ color: '#1e2d4e' }}>Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">By using OUTSYD, you agree to these terms. OUTSYD is provided as-is for informational and planning purposes only.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold" style={{ color: '#1e2d4e' }}>Service Description</h2>
            <p className="text-slate-600 leading-relaxed">OUTSYD generates parametric construction cost estimates using research-validated coefficients from CPWD DSR 2024 and regional rate indexes. Estimates are approximations — not substitutes for professional engineering assessments.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold" style={{ color: '#1e2d4e' }}>Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">OUTSYD and its creator assume no liability for construction decisions made based on estimates generated by this tool. Users must engage qualified structural engineers and licensed professionals before committing to construction.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold" style={{ color: '#1e2d4e' }}>Intellectual Property</h2>
            <p className="text-slate-600 leading-relaxed">OUTSYD, its coefficient engine, and design are created by Ankit Kumar Tiwari. All rights reserved.</p>
          </section>
        </div>
      </div>
    </main>
  );
}
